version: '3.9'

volumes:
  mdb:
    name: mdb

networks: 
  party:
   name: party
   external: true

services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mdb:/data/db
    ports:
    # external:internal
      - 27017:27017
    restart: always
